---
title: "Deliverables"
author: "Joohee"
date: '2017 11 12 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
getwd()
## Read in the data & Pre-processing


```{r}
data1112 <- read.csv("data1112.csv") ### CHANGE THIS PATH!
sentiment <- read.csv("sentimentscore.csv") ### CHANGE THIS PATH!


data1112 <- merge(data1112, sentiment, by = "PostId", all.x = T)

data1112$likelihood <- 0
data1112$likelihood[data1112$AcceptedAnswerId > 0] <- 1
data1112$likelihood <- as.factor(data1112$likelihood)

# Post(question) characteristics
data1112$postViewcount <- as.numeric(data1112$postViewcount)
data1112$postScore <- as.numeric(data1112$postScore)
data1112$numAnswer <- as.numeric(data1112$numAnswer)
data1112$numComments <- as.numeric(data1112$numComments)
data1112$Favorite <- as.numeric(data1112$Favorite)

# Answerer characteristics
data1112$AnswererReputation <- as.numeric(data1112$AnswererReputation)
data1112$answererProfileViews <- as.numeric(data1112$answererProfileViews)

# Answer characteristics
data1112$avg_ans_score <- as.numeric(data1112$avg_ans_score)
data1112$max_ans_score <- as.numeric(data1112$max_ans_score)

temp <- data1112[,c("postViewcount", "likelihood", "postScore", "numAnswer", "numComments", "Favorite", "AnswererReputation", "answererProfileViews", "avg_ans_score", "max_ans_score", "positivity_score", "negativity_score")]

temp[is.na(temp)] <-0
```

## Divide test set & train set

```{r}
index <- 1:nrow(temp)
testindex <- sample(index, trunc(length(index)/5))
testset <- temp[testindex,]
trainset <- temp[-testindex,]
dim(testset)
dim(trainset)
```

## Run the model without text-mining features

```{r}
library(e1071)
library(cwhmisc)

record_performance <- function(df, name, model, test) {
  print(length(model$fitted))
  svm.pred <- predict(model, newdata = test, probability = TRUE)
  print(length(svm.pred))
  svm.table <- table(pred = svm.pred, true=testset$likelihood)
  print(dim(svm.table))
  df <- rbind(df, data.frame(model=c(name), score=c(classAgreement(svm.table)$diag)))
  print(dim(df))
  return(df)
}
```

## SVM model performance test

```{r}
mfc_baseline <- sum(testset$likelihood == 0) / nrow(testset)
results <- data.frame(model=c("MFC"), score=c(mfc_baseline)) ## Baseline performance


results <- record_performance(results, "all_var", svm(likelihood ~ .- likelihood, data = trainset, probability = TRUE), testset) ## models before feature engineering
```

```{r}
results
```

